### ISSUE TITLE
Issue with ILO codelist

### ISSUE THREAD

**Issue by osirello** [Meaningful-Data/sdmxthon#35]
Running the following does not return any code

`import sdmxthon message = sdmxthon.read_sdmx("https://www.ilo.org/sdmx/rest/codelist/ILO/CL_AREA/1.0?detail=full") message.content["Codelists"]['ILO:CL_AREA(1.0)'].items`

However, running the same code for Eurostat seems to work properly:
`message = sdmxthon.read_sdmx("https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/codelist/ESTAT/GEO/1.0?detail=full") message.content["Codelists"]['ESTAT:GEO(1.0)'].items`

Could you kindly help with this issue? Thank you

**Comment by antonio-olleros** [comment]
Hi Oliver,
Thanks a lot for reporting this issue, we'll take care of it.

**Comment by antonio-olleros** [comment]
Hi Oliver, we have identified the issue. We were relying on the urns of the codes, but actually ILO response does not include urn for them, that's why they were not created. We will create a new version fixing the issue as soon as possible

**Comment by osirello** [comment]
Dear @antonio-olleros, thank you very much for spotting this. Looking forward to the new release

**Comment by javihern98** [comment]
Hi @osirello . Version 2.3 includes a fix for this issue. Thanks for your support!

**Comment by osirello** [comment]
Thank you very much @javihern98 and @antonio-olleros for taking care of this. I confirm it works well. Thank you.
