### ISSUE TITLE
Error with Dataset object initialization

### ISSUE THREAD

**Issue by gauravcusp** [Meaningful-Data/sdmxthon#58]
I'm following the [notebook](https://github.com/Meaningful-Data/sdmxthon/blob/master/notebooks/sdmxthon_comprehensive_example.ipynb) for SDMX comprehensive example, but I keep getting an error while initializing the Dataset object. (See attached)

Any thoughts on how this can be resolved?

![image](https://github.com/Meaningful-Data/sdmxthon/assets/31963299/4998f301-d0a6-4ba8-8254-8ca46e6524b0)

**Comment by javihern98** [comment]
Hi @gauravcusp , thanks for reporting this!

I will update the sdmxthon comprehensive example, this has outdated code. Please ensure you have in the same directory the input_data.csv to prevent errors.

**Comment by javihern98** [comment]
Hi @gauravcusp, please check it again -> [SDMX Comprehensive Example](https://github.com/Meaningful-Data/sdmxthon/blob/master/notebooks/sdmxthon_comprehensive_example.ipynb)

**Comment by javihern98** [comment]
Closing this issue as it is solved
